[package]
name = "codo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
dirs = "3.0"
env_logger = "0.8.4"
log = "0.4.14"
users = "0.11"
yaml-rust = "0.4"
